default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: demo_elastic

test:
  <<: *default
  database: test_elastic

production:
  <<: *default
  database: production_elastic
